# site settings
title: Rheza Budiono's blog
email: rheza@uchicago.edu
description: ""
url: "http://rhezab.github.io"
github_username: rhezab
google_analytics: UA-105596202-1

# build settings
markdown: python-markdown-parser
permalink: pretty


