# site settings
title: Rheza's working notes
email: rheza@uchicago.edu
description: ""
url: "http://rhezab.github.io"
github_username: rhezab

# build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# plugins
plugins:
  - jekyll-relative-links

# collections
collections:
  notes:
    output: true
